backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "home"
    label: "Conteúdo da Home"
    delete: false
    editor:
      preview: false
    files:
      - file: "content/home.json"
        label: "Home"
        name: "home"
        format: "json"
        fields:
          - label: "Carrossel"
            name: "carousel"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descrição", name: "desc", widget: "string", required: false}
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Link", name: "link", widget: "string", required: false}
          - label: "Notícias"
            name: "noticias"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Slug (sem espaços)", name: "slug", widget: "string"}
              - {label: "Resumo", name: "desc", widget: "string", required: false}
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Link externo (opcional)", name: "link", widget: "string", required: false}
              - {label: "Conteúdo (Markdown)", name: "body", widget: "markdown"}
          - label: "Patrocinadores"
            name: "patrocinadores"
            widget: "list"
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Descrição", name: "desc", widget: "string", required: false}
          - label: "Galeria"
            name: "galeria"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Legenda", name: "caption", widget: "string", required: false}
